"""
GraphQL types for Device operations.
"""

from datetime import datetime
from typing import Optional

import strawberry

from app.graphql.types.base import ConnectionStatus


@strawberry.type
class DeviceType:
    """Device information."""

    id: str
    serial_number: str  # MAC address
    device_type: str
    firmware_version: str
    battery_level: Optional[int] = None
    connection_status: ConnectionStatus
    is_active: bool
    paired_at: Optional[datetime] = None
    child_id: Optional[str] = None
    child_name: Optional[str] = None
    created_at: datetime
    updated_at: Optional[datetime] = None


@strawberry.input
class RegisterDeviceInput:
    """Input for device registration."""

    serial_number: str  # MAC address from BLE
    device_secret: str  # Generated by device
    device_type: str
    firmware_version: str
    child_id: str  # Child to pair with


@strawberry.type
class RegisterDevicePayload:
    """Response for device registration."""

    success: bool
    device: Optional[DeviceType] = None
    error_code: Optional[str] = None
    error_message: Optional[str] = None


@strawberry.type
class UnpairDevicePayload:
    """Response for device unpairing."""

    success: bool
    error_code: Optional[str] = None
    error_message: Optional[str] = None
