"""Initial schema: users, children, devices, subscriptions

Revision ID: 4914e5ef88b4
Revises: 
Create Date: 2025-12-15 12:25:59.655439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4914e5ef88b4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique user identifier'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address (unique, used for login)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hashed password'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Parent's full name"),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Optional phone number'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Account active status (soft delete flag)'),
    sa.Column('email_verified', sa.Boolean(), nullable=False, comment='Email verification status'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_table('children',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique child identifier'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Parent account reference'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Child's name (TODO: Add encryption at rest)"),
    sa.Column('birth_date', sa.Date(), nullable=False, comment="Child's birthdate (TODO: Add encryption at rest)"),
    sa.Column('gender', sa.String(length=20), nullable=True, comment='Optional gender'),
    sa.Column('personality_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='AI-analyzed personality traits (flexible schema)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Profile active status (soft delete flag)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.CheckConstraint('birth_date <= CURRENT_DATE', name='chk_children_age'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Child profiles with AI-analyzed personality data'
    )
    op.create_index(op.f('ix_children_birth_date'), 'children', ['birth_date'], unique=False)
    op.create_index(op.f('ix_children_user_id'), 'children', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique subscription identifier'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User account reference (one-to-one)'),
    sa.Column('plan_type', sa.String(length=20), nullable=False, comment='Subscription plan: free/basic/premium'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Subscription status: active/cancelled/expired/trial'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='Subscription start date'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Expiration date (null = lifetime/no expiry)'),
    sa.Column('auto_renew', sa.Boolean(), nullable=False, comment='Auto-renewal flag'),
    sa.Column('payment_method_id', sa.String(length=100), nullable=True, comment='Stripe/Toss payment method ID'),
    sa.Column('usage_limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Voice minutes, API calls, and other usage limits'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.CheckConstraint("plan_type IN ('free', 'basic', 'premium')", name='chk_plan_type'),
    sa.CheckConstraint("status IN ('active', 'cancelled', 'expired', 'trial')", name='chk_status'),
    sa.CheckConstraint('expires_at IS NULL OR expires_at > started_at', name='chk_subscription_dates'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='User subscription plans with usage limits'
    )
    op.create_index('idx_subscriptions_expiry', 'subscriptions', ['expires_at'], unique=False, postgresql_where=sa.text('expires_at IS NOT NULL'))
    op.create_index('idx_subscriptions_plan', 'subscriptions', ['plan_type'], unique=False)
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique device identifier'),
    sa.Column('serial_number', sa.String(length=50), nullable=False, comment='Hardware serial number (unique identifier)'),
    sa.Column('device_secret', sa.String(length=255), nullable=False, comment='HMAC authentication secret (stored securely)'),
    sa.Column('child_id', sa.UUID(), nullable=True, comment='Paired child reference (nullable when unpaired)'),
    sa.Column('device_type', sa.String(length=50), nullable=False, comment='Device model type'),
    sa.Column('firmware_version', sa.String(length=20), nullable=False, comment='Current firmware version'),
    sa.Column('battery_level', sa.Integer(), nullable=True, comment='Current battery percentage (0-100)'),
    sa.Column('connection_status', sa.String(length=20), nullable=False, comment='Connection status: online/offline/sleep'),
    sa.Column('last_seen', sa.DateTime(), nullable=True, comment='Last connection timestamp'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Device activation status'),
    sa.Column('paired_at', sa.DateTime(), nullable=True, comment='When device was paired with current child'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Timestamp when the record was last updated'),
    sa.CheckConstraint("connection_status IN ('online', 'offline', 'sleep')", name='chk_connection_status'),
    sa.CheckConstraint('battery_level >= 0 AND battery_level <= 100', name='chk_battery_range'),
    sa.ForeignKeyConstraint(['child_id'], ['children.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Smart toy devices with HMAC authentication'
    )
    op.create_index('idx_devices_battery', 'devices', ['battery_level'], unique=False, postgresql_where=sa.text('battery_level < 20'))
    op.create_index('idx_devices_status', 'devices', ['connection_status', 'last_seen'], unique=False)
    op.create_index('idx_devices_unique_child', 'devices', ['child_id'], unique=True, postgresql_where=sa.text('child_id IS NOT NULL AND is_active = true'))
    op.create_index(op.f('ix_devices_child_id'), 'devices', ['child_id'], unique=False)
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.drop_index(op.f('ix_devices_child_id'), table_name='devices')
    op.drop_index('idx_devices_unique_child', table_name='devices', postgresql_where=sa.text('child_id IS NOT NULL AND is_active = true'))
    op.drop_index('idx_devices_status', table_name='devices')
    op.drop_index('idx_devices_battery', table_name='devices', postgresql_where=sa.text('battery_level < 20'))
    op.drop_table('devices')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_index('idx_subscriptions_plan', table_name='subscriptions')
    op.drop_index('idx_subscriptions_expiry', table_name='subscriptions', postgresql_where=sa.text('expires_at IS NOT NULL'))
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_children_user_id'), table_name='children')
    op.drop_index(op.f('ix_children_birth_date'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
